name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: yarn build
      - name: Set version variable
        run: |
          node -e "console.log('version='+JSON.parse(require('fs').readFileSync('package.json')).version)" >> $GITHUB_ENV
      - name: Upload Chromium build artifact
        uses: actions/upload-artifact@v2
        with:
          name: chromium_v${{ env.version }}_${{ github.sha }}
          path: dist/chromium
      - name: Upload Firefox build artifact
        uses: actions/upload-artifact@v2
        with:
          name: firefox_v${{ env.version }}_${{ github.sha }}
          path: dist/firefox
